package com.mudrahome.mhlms.enums;

public enum UploadLeadEnum {
    FILL_CONTACT, UPLOAD_LEAD,
    FILL_NAME, FILL_LOAN_AMOUNT,
    FILL_CALLER_REMARKS, SET_REMINDER,
    SET_EMPLOYMENT, SET_EMPLOYMENT_TYPE,
    SET_LOAN_TYPE, SET_PROPERTY_TYPE,
    SET_LOCATION, SET_ALARM,
    SET_ASSIGNEE
}